[package]
name = "rustron"
version = "0.1.0"
authors = ["Maxwell L-T <maxwell.lt@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
telnet = "0.1.4"
anyhow = "1.0.39"
rocket = "0.4.7"
